[config]   
interval = 70
homedir = '/home/ubuntu/sotaapp/backend/'
logdir = '/var/log/potaspots/'
logname = 'potaspots.log'
localtz = "Asia/Tokyo"
alerts = "08:00"
summary = "21:00"
nostr_relay_servers = [ "wss://nostr.mom", "wss://relay.damus.io", "wss://nostr-pub.wellorder.net", "wss://nos.lol"]

[config.pota]
summary = 21
suppress_interval = 900
storage_period =  7
filter =  'JA*'

[config.sota]
summary = 21
suppress_interval = 60
storage_period = 7
filter =  'JA*'

[accesskeys.pota] 
consumer = ''
consumer_sec = ''
access = ''
access_sec = ''
mastodon_access_token = ''
mastodon_api_base_url = ''
nostr_private_key = ''

[accesskeys.sota]
consumer = ''
consumer_sec = ''
access = ''
access_sec = ''
mastodon_access_token = ''
mastodon_api_base_url = ''
nostr_private_key = ''


